services:
  db:
    image: postgres:16
    container_name: postgres_otp
    restart: always
    environment:
      POSTGRES_USER: otpuser
      POSTGRES_PASSWORD: otppass123
      POSTGRES_DB: otpdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U otpuser -d otpdb" ]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

  api:
    build: .
    container_name: fastapi_otp
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      .env

volumes:
  postgres_data: